### ISSUE TITLE
[critical] Human factor blocking awesome posts

### ISSUE THREAD

**Issue by ghost** [cymruu/anonimowemirkowyznania#14]
Niestety, system nie jest odporny na niepełnosprawność intelektualną moderatorów. Parę razy zakładałem wyznanie z bardzo fajnym tekstem i za każdym razem dostaję "Oznaczono jako treść niebezpieczna" bez możliwości odwołania się, uzyskania wyjaśnień itd.

**Comment by cymruu** [comment]
Śmiało, czekam na pull request z rozwiązaniem problemu. 
A tak serio to może odezwij się do mnie na priv, albo na maila jak się wstydzisz i napisz o co dokładnie chodzi. Sporo rzeczy odrzucamy, no i rzeczywiście błędy mogą się zdarzyć.

**Comment by ghost** [comment]
Nie będzie pull request. Do kodu nie została dołączona licencja, więc wygląda mi on na public domain. Jeżeli będę chciał zaimplementować zmianę, zrobię to na zamkniętym forku.

**Comment by cymruu** [comment]
@programista15k śmiało, licencja to MIT więc możesz na tym nawet zacząć zarabiać. 
Dzięki za uświadomienie, że brakuje tej informacji. Postaram się ją dodać w najbliższym czasie.
BTW jeśli nie ma informacji o licencji to nie możesz zakładać, że jest public domain.
