### ISSUE TITLE
Lista uczestników

### ISSUE THREAD

**Issue by Widziks92** [cymruu/anonimowemirkowyznania#18]
<img width="1449" alt="screenshot 2019-03-06 at 17 09 39" src="https://user-images.githubusercontent.com/18347466/53895633-c211ce00-4032-11e9-840f-f541b11f87cd.png">

Przy dodawaniu komentarza lista uczestników nie zawija się

**Comment by cymruu** [comment]
Naprawiono w b14ce1173994758b0ea1ae44040f8e3ec9abace9
