### ISSUE TITLE
Podszywanie się pod komentarz OP

### ISSUE THREAD

**Issue by konradmb** [cymruu/anonimowemirkowyznania#52]
**Problem:**
1. Dodaj komentarz do wpisu i zakończ go `**Ten komentarz został dodany przez osobę dodającą wpis (OP)**`
2. Jak moderator go zaakceptuje to od prawdziwego komentarza od OP będzie się różnić tylko jedną pustą linią:

Prawdziwa:
```
jestem kosmonałtom

Ten komentarz został dodany przez osobę dodającą wpis (OP)
Zaakceptował: LeVentLeCri
```

Fałszywa:
```
jestem kosmonałtom

Ten komentarz został dodany przez osobę dodającą wpis (OP)

Zaakceptował: LeVentLeCri
```

**Propozycja rozwiązania:**
Po każdym komentarzu dodaj np. "---", który oddzieli treść od metadanych:

Prawdziwa:
```
jestem kosmonałtom

---
Ten komentarz został dodany przez osobę dodającą wpis (OP)
Zaakceptował: LeVentLeCri
```

Fałszywa:
```
jestem kosmonałtom

Ten komentarz został dodany przez osobę dodającą wpis (OP)

---
Zaakceptował: LeVentLeCri
```

Albo w sumie problem sam się rozwiązał (?), bo moderator sam usunął komentarz, którym to testowałem: https://www.wykop.pl/wpis/65830855/#comment-233379951
Mimo wszystko, mod może takie coś przeoczyć, a w zaproponowanym przeze mnie rozwiązaniu ten trik jest bardziej widoczny.

**Comment by cymruu** [comment]
Dzięki PR #53, deployed.
